# configuration in this file is shared by all hosts

{ pkgs, ... }: {

  # sops-nix: use SSH host key for system-level secret decryption (runs as root, no passphrase)
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  # sshd refuses to serve a host key that is not 0600, so the key itself stays
  # root-only. For home-manager sops activation (runs as wrbbz), derive the
  # equivalent age identity from it at boot instead: same recipient all sops
  # files are already encrypted to, but it cannot be used to impersonate sshd.
  systemd.tmpfiles.rules = [
    "z /etc/ssh/ssh_host_ed25519_key 0600 root root -"
  ];
  systemd.services.sops-age-key-wrbbz = {
    description = "Derive wrbbz's sops age key from the SSH host key";
    wantedBy = [ "multi-user.target" ];
    after = [ "sshd.service" ]; # host keys are generated by sshd's preStart on first boot
    before = [ "home-manager-wrbbz.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      install -d -m 700 -o wrbbz /var/lib/sops-wrbbz
      ${pkgs.ssh-to-age}/bin/ssh-to-age -private-key \
        -i /etc/ssh/ssh_host_ed25519_key -o /var/lib/sops-wrbbz/keys.txt
      chown wrbbz /var/lib/sops-wrbbz/keys.txt
      chmod 400 /var/lib/sops-wrbbz/keys.txt
    '';
  };

  users.users = {
    root = {
      initialHashedPassword = "$6$o.yY8ETd3VmTj2n4$APQjNsOuNsbheay7H4CEg7hbG7TfISDnR/mGuz6xuPQr9HpKm8Nx0CEHwLmFhDD6ZdNQ/CmZvvz48JmQhgfoi/";
      openssh.authorizedKeys.keys = [ "sshKey_placeholder" ];
    };
  };

  users.users.wrbbz = {
    initialHashedPassword = "!";
    isNormalUser = true;
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    shell = pkgs.zsh;
  };

  home-manager.users.wrbbz = {
    home.username = "wrbbz";
    home.stateVersion = "26.05";
  };

  ## enable ZFS auto snapshot on datasets
  ## You need to set the auto snapshot property to "true"
  ## on datasets for this to work, such as
  # zfs set com.sun:auto-snapshot=true rpool/nixos/home
  services.zfs = {
    autoSnapshot = {
      enable = false;
      flags = "-k -p --utc";
      monthly = 48;
    };
  };

  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
  };

  services.openssh = {
    enable = true;
    settings = { PasswordAuthentication = false; };
  };

  boot.zfs.forceImportRoot = false;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  programs.git.enable = true;

  security = {
    doas ={
      enable = true;
      extraRules = [{
        users = ["wrbbz"];
        persist = true;
      }];
    };
    sudo.enable = false;
    polkit.enable = true;
  };

  environment.systemPackages = builtins.attrValues {
    inherit (pkgs)
      cryptsetup
    ;
  };

  fonts = {
    packages = with pkgs; [
      nerd-fonts.fira-code
      nerd-fonts.hack
      noto-fonts-color-emoji
    ];
    fontconfig = {
      enable = true;
      defaultFonts = {
        serif = [ "Hack" ];
        sansSerif = [ "Hack" ];
        monospace = [ "Fira" ];
        emoji = [ "NotoColorEmoji" ];
      };
    };
  };

  i18n = {
    defaultLocale = "en_US.UTF-8";
    extraLocaleSettings = {
      LC_ADDRESS = "en_US.UTF-8";
      LC_IDENTIFICATION = "en_US.UTF-8";
      LC_MEASUREMENT = "en_US.UTF-8";
      LC_MONETARY = "en_US.UTF-8";
      LC_NAME = "en_US.UTF-8";
      LC_NUMERIC = "en_US.UTF-8";
      LC_PAPER = "en_US.UTF-8";
      LC_TELEPHONE = "en_US.UTF-8";
      LC_TIME = "en_US.UTF-8";
    };
  };

  networking = {
    nftables.enable = true;
    firewall.enable = true;
  };
}
